# Generated by Django 5.0.4 on 2024-05-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_product_host_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.FloatField(default=150),
        ),
        migrations.AddField(
            model_name='order',
            name='total_items',
            field=models.IntegerField(null=True),
        ),
    ]
